kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cron-hpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cron-hpa
subjects:
  - kind: ServiceAccount
    name: cron-hpa
    namespace: {{ .Release.Namespace }}
